sshrc changes for yubikey login, vimrc tweak

diff --git a/ssh_myrc b/ssh_myrc
--- a/ssh_myrc
+++ b/ssh_myrc
@@ -2,16 +2,41 @@
 
 # Fix SSH auth socket location so agent forwarding works with tmux
 echo "Looking at sockets and SSH_AUTH_SOCK currently set at $SSH_AUTH_SOCK"
-
 ssh-add -l
 if [[ $? -eq 2 ]]; then
-    echo "Cannot connect to agent. Unsetting $SSH_AUTH_SOCK"
-    unset SSH_AUTH_SOCK
+ 	echo "Cannot connect to agent. Unsetting $SSH_AUTH_SOCK"
+ 	unset SSH_AUTH_SOCK
         echo "Removing stale SSH_AUTH_SOCK"
         rm -f ~/.ssh/ssh_auth_sock
         unset SSH_AUTH_SOCK
-        eval $(ssh-agent -s) && ssh-add -A
+	eval $(gpg-agent --homedir /home/fblaise/.gnupg --daemon)
         ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock 2>/dev/null
         export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
-#	echo "Now, add your key to the agent."
+	echo "Now, add your key to the agent."
 fi
+
+# prior to yubikey and gpg-agent
+# if [[ $? -eq 2 ]]; then
+# 	echo "Cannot connect to agent. Unsetting $SSH_AUTH_SOCK"
+# 	unset SSH_AUTH_SOCK
+#         echo "Removing stale SSH_AUTH_SOCK"
+#         rm -f ~/.ssh/ssh_auth_sock
+#         unset SSH_AUTH_SOCK
+#         eval $(ssh-agent -s)
+#         ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock 2>/dev/null
+#         export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
+# 	echo "Now, add your key to the agent."
+# fi
+# 
+# # Taken from the sshd(8) manpage.
+# if read proto cookie && [ -n "$DISPLAY" ]; then
+#         if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
+#                 # X11UseLocalhost=yes
+#                 echo add unix:`echo $DISPLAY |
+#                     cut -c11-` $proto $cookie
+#         else
+#                 # X11UseLocalhost=no
+#                 echo add $DISPLAY $proto $cookie
+#         fi | xauth -q -
+#fi
+
